###################################
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.
###################################

def product_finder(factors, limit):
    product_list = []
    x = 0
    if 0 in factors:
        print('Cannot have a zero as one of the factors.')
    else:
        while x < len(factors):
            if factors[x] > limit:
                print('Cannot have a factor larger than the limit value.')
                exit()
            multiplier = 1
            while multiplier <= limit:
                if factors[x] * multiplier <= limit and factors[x] * multiplier not in product_list:
                    product_list.append(factors[x] * multiplier)
                else:
                    break
                multiplier += 1
            x += 1
        product_list.sort()
        print(product_list)


product_finder([2001, 5032, 8674], 10000)

