###################################
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.
###################################

def product_finder_2(factors, limit):
    products = []
    x = 0
    while x < len(factors):
        counter = 1
        while counter <= limit:
            if counter % factors[x] == 0 and counter not in products:
                products.append(counter)
            counter += 1
        x += 1

    products.sort()
    print('The Products of', factors, 'less than or equal to', limit, 'are:', products)


product_finder_2([1337, 2257, 8000], 10000)

