###################################
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.
###################################

def product_finder(factor1, factor2, limit):
    x = 1
    product_list = []

    while x <= limit:
        if x % factor1 == 0 or x % factor2 == 0:
            product_list.append(x)
        x += 1

    print('There are', len(product_list), 'products of', factor1, 'and', factor2,
          'less than or equal to', limit, ':', product_list)


product_finder(13, 237, 10000)